-- MySQL Script generated by MySQL Workbench
-- Thu Apr 29 14:34:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vacina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vacina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vacina` DEFAULT CHARACTER SET utf8 ;
USE `vacina` ;

-- -----------------------------------------------------
-- Table `vacina`.`estadoCivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`estadoCivil` (
  `idestadoCivil` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestadoCivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`distrito` (
  `iddistrito` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iddistrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`sexoGenetico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`sexoGenetico` (
  `idsexoGenetico` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsexoGenetico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`religiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`religiao` (
  `idreligiao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idreligiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`habitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`habitante` (
  `idhabitante` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `nomeMae` VARCHAR(45) NULL,
  `endereco` LONGTEXT NULL,
  `escolaridade` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NULL,
  `planoSaude` INT NOT NULL,
  `numeroSUS` VARCHAR(45) NOT NULL,
  `estadoCivil_idestadoCivil` INT NOT NULL,
  `distrito_iddistrito` INT NOT NULL,
  `sexoGenetico_idsexoGenetico` INT NOT NULL,
  `religiao_idreligiao` INT NOT NULL,
  UNIQUE INDEX `numeroSUS_UNIQUE` (`numeroSUS` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `idhabitante_UNIQUE` (`idhabitante` ASC) VISIBLE,
  PRIMARY KEY (`idhabitante`),
  INDEX `fk_habitante_estadoCivil_idx` (`estadoCivil_idestadoCivil` ASC) VISIBLE,
  INDEX `fk_habitante_distrito1_idx` (`distrito_iddistrito` ASC) VISIBLE,
  INDEX `fk_habitante_sexoGenetico1_idx` (`sexoGenetico_idsexoGenetico` ASC) VISIBLE,
  INDEX `fk_habitante_religiao1_idx` (`religiao_idreligiao` ASC) VISIBLE,
  CONSTRAINT `fk_habitante_estadoCivil`
    FOREIGN KEY (`estadoCivil_idestadoCivil`)
    REFERENCES `vacina`.`estadoCivil` (`idestadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitante_distrito1`
    FOREIGN KEY (`distrito_iddistrito`)
    REFERENCES `vacina`.`distrito` (`iddistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitante_sexoGenetico1`
    FOREIGN KEY (`sexoGenetico_idsexoGenetico`)
    REFERENCES `vacina`.`sexoGenetico` (`idsexoGenetico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitante_religiao1`
    FOREIGN KEY (`religiao_idreligiao`)
    REFERENCES `vacina`.`religiao` (`idreligiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`convenio` (
  `idconvenio` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cobertura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconvenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`habitante_has_convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`habitante_has_convenio` (
  `habitante_idhabitante` INT NOT NULL,
  `convenio_idconvenio` INT NOT NULL,
  PRIMARY KEY (`habitante_idhabitante`, `convenio_idconvenio`),
  INDEX `fk_habitante_has_convenio_convenio1_idx` (`convenio_idconvenio` ASC) VISIBLE,
  INDEX `fk_habitante_has_convenio_habitante1_idx` (`habitante_idhabitante` ASC) VISIBLE,
  CONSTRAINT `fk_habitante_has_convenio_habitante1`
    FOREIGN KEY (`habitante_idhabitante`)
    REFERENCES `vacina`.`habitante` (`idhabitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitante_has_convenio_convenio1`
    FOREIGN KEY (`convenio_idconvenio`)
    REFERENCES `vacina`.`convenio` (`idconvenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`tipoVacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`tipoVacina` (
  `idtipoVacina` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoVacina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`laboratorio` (
  `idlaboratorio` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`vacina` (
  `idvacina` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `lote` VARCHAR(45) NOT NULL,
  `quatidadeDoses` INT NOT NULL,
  `dataFabricacao` DATE NOT NULL,
  `dataValidade` DATE NOT NULL,
  `tipoVacina_idtipoVacina` INT NOT NULL,
  `laboratorio_idlaboratorio` INT NOT NULL,
  PRIMARY KEY (`idvacina`),
  INDEX `fk_vacina_tipoVacina1_idx` (`tipoVacina_idtipoVacina` ASC) VISIBLE,
  INDEX `fk_vacina_laboratorio1_idx` (`laboratorio_idlaboratorio` ASC) VISIBLE,
  CONSTRAINT `fk_vacina_tipoVacina1`
    FOREIGN KEY (`tipoVacina_idtipoVacina`)
    REFERENCES `vacina`.`tipoVacina` (`idtipoVacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacina_laboratorio1`
    FOREIGN KEY (`laboratorio_idlaboratorio`)
    REFERENCES `vacina`.`laboratorio` (`idlaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`habitante_has_vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`habitante_has_vacina` (
  `habitante_idhabitante` INT NOT NULL,
  `vacina_idvacina` INT NOT NULL,
  PRIMARY KEY (`habitante_idhabitante`, `vacina_idvacina`),
  INDEX `fk_habitante_has_vacina_vacina1_idx` (`vacina_idvacina` ASC) VISIBLE,
  INDEX `fk_habitante_has_vacina_habitante1_idx` (`habitante_idhabitante` ASC) VISIBLE,
  CONSTRAINT `fk_habitante_has_vacina_habitante1`
    FOREIGN KEY (`habitante_idhabitante`)
    REFERENCES `vacina`.`habitante` (`idhabitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitante_has_vacina_vacina1`
    FOREIGN KEY (`vacina_idvacina`)
    REFERENCES `vacina`.`vacina` (`idvacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`alergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`alergia` (
  `idalergia` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalergia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacina`.`habitante_has_alergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacina`.`habitante_has_alergia` (
  `habitante_idhabitante` INT NOT NULL,
  `alergia_idalergia` INT NOT NULL,
  PRIMARY KEY (`habitante_idhabitante`, `alergia_idalergia`),
  INDEX `fk_habitante_has_alergia_alergia1_idx` (`alergia_idalergia` ASC) VISIBLE,
  INDEX `fk_habitante_has_alergia_habitante1_idx` (`habitante_idhabitante` ASC) VISIBLE,
  CONSTRAINT `fk_habitante_has_alergia_habitante1`
    FOREIGN KEY (`habitante_idhabitante`)
    REFERENCES `vacina`.`habitante` (`idhabitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habitante_has_alergia_alergia1`
    FOREIGN KEY (`alergia_idalergia`)
    REFERENCES `vacina`.`alergia` (`idalergia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
